const mongoose = require('mongoose');

const triageSchema = new mongoose.Schema({
    patientId: { 
        type: String, 
        required: true, 
        unique: true 
    },
    // The exact, raw data submitted by the frontend form
    rawIntake: { 
        type: mongoose.Schema.Types.Mixed, 
        required: true 
    },
    // The structured clinical reasoning generated by Mistral
    llmTriage: { 
        type: mongoose.Schema.Types.Mixed, 
        required: true 
    },
    createdAt: { 
        type: Date, 
        default: Date.now 
    }
});

module.exports = mongoose.model('Triage', triageSchema);
